var questions = [
    {
        "question": "Marriage is solely defined as the conjoinment of a man and woman.",
        "score_effect": {
            "Religious" : 50,
            "Tradition" : 50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "There should be seperation between Church and State.",
        "score_effect": {
            "Religious" : -50,
            "Tradition" : -50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : -50,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Churches should be taxed.",
        "score_effect": {
            "Religious" : -50,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 50,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "There should be a higher barrier to entry to be considered a religion in the United States.",
        "score_effect": {
            "Religious" : -50,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 50,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "There should be increased regulation on what is taught in religious schools.",
        "score_effect": {
            "Religious" : -50,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 50,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Parents of children who attend private schools should not pay taxes towards public schools.",
        "score_effect": {
            "Religious" : 50,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : -50,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Priests should be made mandatory reporters of abuse, even abuse admitted during confession.",
        "score_effect": {
            "Religious" : -50,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 50,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Science takes a higher priority than faith.",
        "score_effect": {
            "Religious" : -50,
            "Tradition" : -50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Religion and morals go hand in hand.",
        "score_effect": {
            "Religious" : 50,
            "Tradition" : 50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Someone who is not religious is not moral.",
        "score_effect": {
            "Religious" : 50,
            "Tradition" : 50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Tradition should be mostly preserved.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "The 10 commandments should be taught to every child.",
        "score_effect": {
            "Religious" : 50,
            "Tradition" : 50,
            "Respect"   : 50,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Science is a choice.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 50,
            "Respect"   : 50,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "My values trump those of others.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 50,
            "Respect"   : 50,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "My children will be taught my values, and will uphold them as long as they live under my roof.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 50,
            "Respect"   : 50,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "If someone tells me I am wrong based on new information, I will accept that.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : -50,
            "Respect"   : -50,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Change is good.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : -50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Sometimes, the old way is just better.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "Spanking is parenting.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 50,
            "Respect"   : 50,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "If I had children, I would be their friend as well as their parent.",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : -50,
            "Respect"   : -50,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Seclusion" : 0,
        }
    },
    {
        "question": "Gay couples should not be allowed to adopt.",
        "score_effect": {
            "Religious" : 50,
            "Tradition" : 50,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    {
        "question": "0000000000000000000",
        "score_effect": {
            "Religious" : 0,
            "Tradition" : 0,
            "Respect"   : 0,
            "Control"   : 0,
            "Authority" : 0,
            "Federation": 0,
            "Equality"  : 0,
            "Hardship"  : 0,
            "Charity"   : 0,
            "War"       : 0,
            "Seclusion" : 0,
            "Isolation" : 0,
        }
    },
    
];